### ISSUE TITLE
Fix favicon on product website

### ISSUE THREAD

**Issue by nareddyt** [nareddyt/discover-rewards-notifier#14]
On our [product website](http://www.tejunareddy.com/discover-rewards-notifier/), the favicon is not being displayed. I'm not entirely sure why it's not working...

You can view the favicon if you visit http://www.tejunareddy.com/discover-rewards-notifier/favicon.ico. However, it doesn't show up in the tab's favicon image when just visiting http://www.tejunareddy.com/discover-rewards-notifier.

I did add reference to the favicon at the top of `index.html`. Perhaps the reference should be in a different file?

**Comment by nareddyt** [comment]
Note the source code for the product website is in the `docs/` folder

**Comment by supuun** [comment]
It is displayed in my browser

**Comment by nareddyt** [comment]
Hey, welcome! I updated the issue description to make it clearer. I meant that the favicon doesn't show up in the image tab when visiting http://www.tejunareddy.com/discover-rewards-notifier/ or any of it's subpages (like the privacy policy).

Example:

![image](https://user-images.githubusercontent.com/11142171/37295198-c93ddeea-25d4-11e8-9182-9d5fbededc24.png)

**Comment by supuun** [comment]
![capture](https://user-images.githubusercontent.com/11631221/37295484-bfb677c6-2631-11e8-89df-df3f9360bd56.PNG)

**Comment by nareddyt** [comment]
Seems like a caching issue: https://stackoverflow.com/questions/7324456/favicon-not-showing-up

Hoping this works for everyone else, I'll close the issue
