### ISSUE TITLE
Minor changes to the logo

### ISSUE THREAD

**Issue by nareddyt** [nareddyt/discover-rewards-notifier#30]
A user mentioned that the logo represents a **mastercard**, not a **discover card**. We might want to change the logo to resemble discover.

Requirements:

- Changes should be minimal. We want the logo to look familiar for our current users.
- We cannot use copyrighted material / images

**Comment by rbkent07** [comment]
I updated the images, but I am unsure how to update them in the repository. I have attached the files here. Hopefully that works. I'm kind of new to GitHub, so bear with me.

![prod-icon-38](https://user-images.githubusercontent.com/39812648/40867134-95eda498-65c7-11e8-8c2f-9dd25e6199f1.png)
![prod-icon-512](https://user-images.githubusercontent.com/39812648/40867136-9b9190c6-65c7-11e8-9666-c0a4bc31fb83.png)
![store-icon-128-border](https://user-images.githubusercontent.com/39812648/40867138-a117caba-65c7-11e8-9f54-dbc4abbc6b32.png)

**Comment by nareddyt** [comment]
I see you were able to commit the images via the Github web ui, but it's also useful to learn how to do it with just git on your machine! We can go over that.

So that could be caused by a lot of reasons, but perhaps you are specifying the file paths incorrectly? Make sure you are in the root directory of the project, and then do a `git add .` (with the period). This will add **all** changed files automatically. If you do a `git status` then you should see all the changed files show up in green.

**Comment by nareddyt** [comment]
Closing because PR #76 is merged. Feel free to comment if you have any more problems with git.

**Comment by rbkent07** [comment]
Thank you for the tips. I'll try that next time. I'm new to Git and GitHub,
but it's fun to learn new things.
