### ISSUE TITLE
Don't remove prefixes on all site names

### ISSUE THREAD

**Issue by nareddyt** [nareddyt/discover-rewards-notifier#83]
We made PR #81 to fix issue #69, but there's a tiny bug in the code. That bug would result in the `ignored_names` list not being checked, so names like `Hotels.com` would still be truncated.

Should be a quick fix that @MikeM711 will take care of.

**Comment by nareddyt** [comment]
For reference, quote from @MikeM711 in PR #81:
> ...Spoke a little too soon https://github.com/nareddyt/discover-rewards-notifier/blob/master/tools/dataProcessor.js#L234
> item.site_name should be item as I noticed in the JSON that Hotels was not Hotels.com😓
> 
> apologies over here
> 
> I do have the updated fork on my end: 7c495ff
> 
> Let me know what you want me to do!

**Comment by MikeM711** [comment]
PR #84 should fix it!
